### PR TITLE
Feature/virtualenv

### PR DESCRIPTION
**Pull request by danimtb**
Just reviewed your PR and looks really good!

This is just to keep it updated with develop and bring some minor fixes on linting as well as "unset" in *deactivate-sh* files

### CODE REVIEW

**Comment by niosHD** [comment]
Thank you very much @danimtb for the update and the style fixes, I really appreciate it since I am currently short on time! The overall change looks good, but I have concerns regarding the testing of the `unset` feature. More specifically, since we currently do not initialize all the variables the unit tests break in environments where one of the "unset" variables is already defined (see for example `PS1=foo nosetests -s conans/test/generators/virtualenv_test.py`). 

Furthermore, I would really appreciate your opinion regarding conan-io/conan#2568. (Sorry @jamezmoran that I can not work on this further at the moment.) I still think that this PR could improve the current situation but it is tricky to get all the checks right. Especially, since there are endless many different environments as I outlined (a few I have available) in conan-io/conan#2638.

**Comment by danimtb** [comment]
Hi @niosHD,

Thank you so much for the answer. Yes, we will start merging this PR and will continue with pending tasks as it would be much harder to do it all at once for us right now.

Regarding the issuee with `unset`:

If I understand it correctly, your examples is modifying the environment of the test so I think it is expected to fail in that way. In the use case a user specify any additional variable affecting or not the activate/deactivate scripts I think the user is the one respoinsible for managing the additional variables in the right way. btw, is it normal that a user modifies PS1 var on the fly?

I might not have understood the issue completely so please clarify if necessary and I'll keep on working to push this PR forward 😃

**Comment by niosHD** [comment]
Sorry, I should have been clearer, the example was only intended to show that I can break the test simply by modifying the environment. Your test currently assumes that various variables (`OLD_PS1`,`PS1`,`BASE_LIST`,...) are undefined when executing the test suite.

My concern is that the result of the test bench becomes dependent on the user environment. However, since we do not control the environment I think that we should also not make any assumptions about it and ensure that all variables get initialized as expected. Anyway, I am absolutely fine with merging the PR as is if you prefer to continue work upstream. Should I merge your PR into mine such that it can be merged upstream?

**Comment by danimtb** [comment]
However, if you dont unset variables created by the activate script the environment will end up with empty but still declared variables as pointed by this test: https://github.com/conan-io/conan/blob/46db81747652efa141e7bf21af6e1bc563be50a8/conans/test/generators/virtualbuildenv_test.py#L12

Yes please, lets merge this one and disccuss it in the original PR. Many thanks!

**Comment by niosHD** [comment]
I absolutely agree with you and, as far as I know, the implementation does the right thing. I just argue that the basic_test is broken as soon as the variable is defined in the environment and I think that should be fixed.

The test currently assumes that all these variables have to be `unset` which is only true when they were not defined in the beginning. Sure, we do not define them as part of the test suite. However, it can easily happen that a user executes our tests suite from a shell where one of the variables is defined and then the suite breaks.

**Pull request merged**
